Deliverable04/Models/Province.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deliverable04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Province()
        {
            this.City = new HashSet<City>();
        }
    
        public int ProvinceID { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City> City { get; set; }
    }
}

Deliverable04/Controllers/ProvincesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Deliverable04.Models;

namespace Deliverable04.Controllers
{
    public class ProvincesController : Controller
    {
        private IBEEHEALTHEntities db = new IBEEHEALTHEntities();

        // GET: Provinces
        public ActionResult Index()
        {
            return View(db.Provinces.ToList());
        }

        // GET: Provinces/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Province province = db.Provinces.Find(id);
            if (province == null)
            {
                return HttpNotFound();
            }
            return View(province);
        }

        // GET: Provinces/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Provinces/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProvinceID,Name")] Province province)
        {
            if (ModelState.IsValid)
            {
                db.Provinces.Add(province);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(province);
        }

        // GET: Provinces/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Province province = db.Provinces.Find(id);
            if (province == null)
            {
                return HttpNotFound();
            }
            return View(province);
        }

        // POST: Provinces/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProvinceID,Name")] Province province)
        {
            if (ModelState.IsValid)
            {
                db.Entry(province).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(province);
        }

        // GET: Provinces/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Province province = db.Provinces.Find(id);
            if (province == null)
            {
                return HttpNotFound();
            }
            return View(province);
        }

        // POST: Provinces/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Province province = db.Provinces.Find(id);
            db.Provinces.Remove(province);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Deliverable04/Views/Provinces/Create.cshtml
@model Deliverable04.Models.Province

@{
    Layout = null;
}

<!DOCTYPE html>

<head>
    <title>Admin</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" onclick="location.href='@Url.Action("Index", "Users")';">Administrator</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a onclick="location.href='@Url.Action("Index", "Users")';">Users CRUD</a></li>
                <li><a onclick="location.href='@Url.Action("Index", "Cities")';"> cities</a></li>
                <li><a onclick="location.href='@Url.Action("Index", "Provinces")';"> Provinces</a></li>
                <li><a onclick="location.href='@Url.Action("Index", "UserTypes")';"> UserType</a></li>
                &nbsp;

                <li>&nbsp;<button class="btn btn-primary" onclick="location.href='@Url.Action("SignIn", "IBEEHEALTH")';"> Sign Out</button></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <h2>Provinces</h2>
    </div>

</body>



<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Province</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Deliverable04/Views/Provinces/Delete.cshtml
@model Deliverable04.Models.Province

@{
    Layout = null;
}

<!DOCTYPE html>


<head>
    <title>Admin</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" onclick="location.href='@Url.Action("Index", "Users")';">Administrator</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a onclick="location.href='@Url.Action("Index", "Users")';">Users CRUD</a></li>
                <li><a onclick="location.href='@Url.Action("Index", "Cities")';"> cities</a></li>
                <li><a onclick="location.href='@Url.Action("Index", "Provinces")';"> Provinces</a></li>
                <li><a onclick="location.href='@Url.Action("Index", "UserTypes")';"> UserType</a></li>
                &nbsp;

                <li>&nbsp;<button class="btn btn-primary" onclick="location.href='@Url.Action("SignIn", "IBEEHEALTH")';"> Sign Out</button></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <h2>Provinces</h2>
    </div>

</body>


<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Province</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Deliverable04/Views/Provinces/Details.cshtml
@model Deliverable04.Models.Province

@{
    Layout = null;
}

<!DOCTYPE html>

<head>
    <title>Admin</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" onclick="location.href='@Url.Action("Index", "Users")';">Administrator</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a onclick="location.href='@Url.Action("Index", "Users")';">Users CRUD</a></li>
                <li><a onclick="location.href='@Url.Action("Index", "Cities")';"> cities</a></li>
                <li><a onclick="location.href='@Url.Action("Index", "Provinces")';"> Provinces</a></li>
                <li><a onclick="location.href='@Url.Action("Index", "UserTypes")';"> UserType</a></li>
                &nbsp;

                <li>&nbsp;<button class="btn btn-primary" onclick="location.href='@Url.Action("SignIn", "IBEEHEALTH")';"> Sign Out</button></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <h2>Provinces</h2>
    </div>

</body>



<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Province</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ProvinceID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Deliverable04/Views/Provinces/Edit.cshtml
@model Deliverable04.Models.Province

@{
    Layout = null;
}

<!DOCTYPE html>

<head>
    <title>Admin</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" onclick="location.href='@Url.Action("Index", "Users")';">Administrator</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a onclick="location.href='@Url.Action("Index", "Users")';">Users CRUD</a></li>
                <li><a onclick="location.href='@Url.Action("Index", "Cities")';"> cities</a></li>
                <li><a onclick="location.href='@Url.Action("Index", "Provinces")';"> Provinces</a></li>
                <li><a onclick="location.href='@Url.Action("Index", "UserTypes")';"> UserType</a></li>
                &nbsp;

                <li>&nbsp;<button class="btn btn-primary" onclick="location.href='@Url.Action("SignIn", "IBEEHEALTH")';"> Sign Out</button></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <h2>Provinces</h2>
    </div>

</body>




<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Province</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ProvinceID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Deliverable04/Views/Provinces/Index.cshtml
@model IEnumerable<Deliverable04.Models.Province>

@{
    Layout = null;
}

<!DOCTYPE html>


<head>
    <title>Admin</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" onclick="location.href='@Url.Action("Index", "Users")';">Administrator</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a onclick="location.href='@Url.Action("Index", "Users")';">Users CRUD</a></li>
                <li><a onclick="location.href='@Url.Action("Index", "Cities")';"> cities</a></li>
                <li><a onclick="location.href='@Url.Action("Index", "Provinces")';"> Provinces</a></li>
                <li><a onclick="location.href='@Url.Action("Index", "UserTypes")';"> UserType</a></li>
                &nbsp;

                <li>&nbsp;<button class="btn btn-primary" onclick="location.href='@Url.Action("SignIn", "IBEEHEALTH")';"> Sign Out</button></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <h2>Provinces</h2>
    </div>

</body>




<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ProvinceID }) |
                @Html.ActionLink("Details", "Details", new { id=item.ProvinceID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.ProvinceID })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>